import numpy as np
print(5*'=-','Criando uma linha da matriz'.upper(),20*'=-')
x = np.array([1, 2, 3, 4, 5, 6])
print(x)
print(type(x))
print(5*'=-', 'Criando uma matriz com mais linhas'.upper(),20*'=-')
y = np.array([[1,2,3,4,5,6],[1,2,3,4,8,9]])
print(y)
print(type(y))
print(5*'=-', 'Criando uma matriz nula'.upper(),20*'=-')
#Shape serve para eu definir ou saber as dimensões da matriz
#No caso de definir é o exemplo abaixo
#No caso de saber é o comando variável.shape ex: x.shape
z = np.zeros(shape = (1,2,2))
print(z)
print(5*'=-', 'Criando uma matriz só com 1s'.upper(),20*'=-')
w = np.ones((2,2))
print(w)
print(5*'=-', 'Criando uma matriz com diagonal principal 1'.upper(),20*'=-')
diagu = np.eye(2)
print(diagu)
print(5*'=-', 'Maior, menor, soma, média simples, desvio padrão e variância dos elementos da matriz'.upper(),20*'=-')
q = np.array([[1,2,3],[0,0,0]])
print(q)
print(f'Maior = {q.max()}')
print(f'Menor = {q.min()}')
print(f'Soma = {q.sum()}')
print(f'Média = {q.mean()}')
print(f'Desvio padrão = {q.std()}')
print(f'Variância = {q.var()}')
print(5*'=-', 'Saber a dimensão'.upper(),20*'=-')
#Para saber a dimensão de um array é o comando variável.ndim ex: x.ndim
print(q.ndim)
print(5*'=-', 'Saber o tipo'.upper(),20*'=-')
#Para saber o tipo armazenamento
#Para especifica-lo basta adicionar uma virgula e colcocar dtype='int16'
s = np.array([[1,2,3,4],[1,2,1,3]])
print(s.dtype)
s = np.array([[1,2,3,4],[1,2,1,3]], dtype='int16')
print(s.dtype)
print(5*'=-', 'Saber o tamanho'.upper(),20*'=-')
s = np.array([[1,2,3,4],[1,2,1,3]])
print(s.dtype)
print(s.itemsize)
s = np.array([[1,2,3,4],[1,2,1,3]], dtype='int16')
print(s.dtype)
print(s.itemsize)
print(5*'=-', 'Saber o tamanho total'.upper(),20*'=-')
print(x.nbytes)